ScriptAlias /sun-moon-api/v2 /var/www/sun-moon-api/cgi-bin/v2
<Directory /var/www/sun-moon-api/cgi-bin>
    Options +ExecCGI
    AddHandler cgi-script .py
    Require all granted
    SetEnv SUN_MOON_EPHEMERIS /var/lib/sun-moon-api/de440s.bsp
</Directory>

